### ISSUE TITLE
Kernel size==4？

### ISSUE THREAD

**Issue by a-runner** [USTC-IMCL/ENVC#1]
Hello, I see that the convolution kernel size of the transformation module in the source code is 4?

**Comment by ZongyuGuo** [comment]
You are right. We set the kernel size = 4 in our model when downsampling and upsampling, and found it works also well. It helps to reduce the parameter number of the P frame model slightly (12M parameters), which also implies our method could achieve better performance by building a stronger structure. But frankly speaking, we developed ENVC for several versions, this setting inherited from a very old version. Perhaps we should have changed it to align with other common codecs.

**Comment by a-runner** [comment]
Thanks for the reply!!!

**Comment by a-runner** [comment]
Thanks for the reply!!!
